version: '3.6'
services:
  postgres:
    image: mdillon/postgis:11
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=testingwithrentals
    ports:
      - "5434:5432"
    volumes:
      - ./sql-init.sql:/docker-entrypoint-initdb.d/sql-init.sql      
  # simple-rentals-api:
    # image: golang:1.21
    # container_name: simple-rentals-api
    # stdin_open: true # docker run -i
    # tty: true        # docker run -t
    # command: bash
    # working_dir: /go/src/simple-rentals-api
    # volumes:
      # - ./:/go/src/simple-rentals-api
    # expose:
      # - 8080
    # ports:
      # - "8082:8080"
    # depends_on:
      # - postgres
    # restart: on-failure:1000 